-- MySQL Script generated by MySQL Workbench
-- Thu Feb 28 20:28:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `profil` VARCHAR(255) NULL,
  `date_inscription` DATETIME NULL,
  `slug` VARCHAR(45) NULL,
  PRIMARY KEY (`id_student`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `mydb`.`student` (`email` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`group` ;

CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `id_group` INT NOT NULL,
  `document_size` INT NULL,
  `note` VARCHAR(45) NULL,
  `datecreation` DATETIME NULL,
  PRIMARY KEY (`id_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`document` ;

CREATE TABLE IF NOT EXISTS `mydb`.`document` (
  `id_document` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `object` VARCHAR(45) NULL,
  `document_url` VARCHAR(45) NULL,
  `id_group` INT NOT NULL,
  `id_student` INT NOT NULL,
  `uploaded_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id_document`),
  CONSTRAINT `fk_document_groupe`
    FOREIGN KEY (`id_group`)
    REFERENCES `mydb`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_Etudiant1`
    FOREIGN KEY (`id_student`)
    REFERENCES `mydb`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_document_groupe_idx` ON `mydb`.`document` (`id_group` ASC);

CREATE INDEX `fk_document_Etudiant1_idx` ON `mydb`.`document` (`id_student` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`note` ;

CREATE TABLE IF NOT EXISTS `mydb`.`note` (
  `id_note` INT NOT NULL AUTO_INCREMENT,
  `presentation` INT NULL,
  `content` INT NULL,
  `explanation` INT NULL,
  `answer` INT NULL,
  `workshop` INT NULL,
  `id_student` INT NOT NULL,
  `id_group` INT NOT NULL,
  `remark` VARCHAR(255) NULL,
  PRIMARY KEY (`id_note`),
  CONSTRAINT `fk_note_Etudiant1`
    FOREIGN KEY (`id_student`)
    REFERENCES `mydb`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_note_groupe1`
    FOREIGN KEY (`id_group`)
    REFERENCES `mydb`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_note_Etudiant1_idx` ON `mydb`.`note` (`id_student` ASC);

CREATE INDEX `fk_note_groupe1_idx` ON `mydb`.`note` (`id_group` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id_question` INT NOT NULL,
  `content` VARCHAR(255) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id_question`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`answer` (
  `id_answer` INT NOT NULL,
  `id_question` INT NOT NULL,
  `id_student` INT NOT NULL,
  `content` VARCHAR(255) NULL,
  PRIMARY KEY (`id_answer`, `id_question`, `id_student`),
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`id_question`)
    REFERENCES `mydb`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_Etudiant1`
    FOREIGN KEY (`id_student`)
    REFERENCES `mydb`.`student` (`id_student`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_answer_question1_idx` ON `mydb`.`answer` (`id_question` ASC);

CREATE INDEX `fk_answer_Etudiant1_idx` ON `mydb`.`answer` (`id_student` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
